#!/bin/bash

# AI News Daily - Vercel Deployment Setup Script
# Run this to configure automatic deployment

set -e

echo "🔧 AI News Daily - Vercel Deployment Setup"
echo "=========================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if vercel is installed
if ! command -v vercel &> /dev/null; then
    echo -e "${YELLOW}Installing Vercel CLI...${NC}"
    npm install -g vercel
fi

# Step 1: Check Vercel login status
echo ""
echo "Step 1: Checking Vercel login status..."
if ! vercel whoami &> /dev/null; then
    echo -e "${YELLOW}Please login to Vercel:${NC}"
    echo "1. Open: https://vercel.com/login"
    echo "2. Login with your GitHub account"
    echo "3. Run: vercel link"
    echo ""
    echo "After linking, this script will help configure the remaining settings."
    exit 0
fi

echo -e "${GREEN}✓ Already logged in to Vercel${NC}"

# Step 2: Link project
echo ""
echo "Step 2: Linking project..."
if [ ! -f .vercel/project.json ]; then
    echo "Linking project..."
    vercel link
fi

# Step 3: Get project info
echo ""
echo "Step 3: Getting project configuration..."

if [ -f .vercel/project.json ]; then
    PROJECT_ID=$(cat .vercel/project.json | grep -o '"projectId":"[^"]*"' | cut -d'"' -f4)
    ORG_ID=$(cat .vercel/project.json | grep -o '"orgId":"[^"]*"' | cut -d'"' -f4)
    
    echo "Project ID: $PROJECT_ID"
    echo "Org ID: $ORG_ID"
    
    # Step 4: Configure environment variables
    echo ""
    echo "Step 4: Configure Environment Variables"
    echo "========================================"
    echo ""
    echo "You need to configure the following in Vercel Dashboard:"
    echo "https://vercel.com/tourscholar/ai-news/settings/environment-variables"
    echo ""
    echo "Required variables:"
    echo ""
    echo "1. GITHUB_ID"
    echo "   Get from: https://github.com/settings/developers"
    echo ""
    echo "2. GITHUB_SECRET"
    echo "   Get from: https://github.com/settings/developers"
    echo ""
    echo "3. GOOGLE_CLIENT_ID"
    echo "   Get from: https://console.cloud.google.com/apis/credentials"
    echo ""
    echo "4. GOOGLE_CLIENT_SECRET"
    echo "   Get from: https://console.cloud.google.com/apis/credentials"
    echo ""
    echo "5. NEXTAUTH_SECRET"
    echo "   Generate with: openssl rand -base64 32"
    echo ""
    echo "6. NEXTAUTH_URL"
    echo "   Set to: https://ai-news-bice.vercel.app"
    echo ""
    echo "7. VERCEL_TOKEN"
    echo "   Get from: https://vercel.com/account/tokens"
    echo ""
    
    # Step 5: Generate GitHub Action secrets
    echo ""
    echo "Step 5: GitHub Actions Secrets"
    echo "=============================="
    echo ""
    echo "Go to: https://github.com/Tourscholar/ai-news/settings/secrets/actions"
    echo ""
    echo "Add these secrets:"
    echo ""
    echo "VERCEL_TOKEN=<from step 4>"
    echo "VERCEL_ORG_ID=$ORG_ID"
    echo "VERCEL_PROJECT_ID=$PROJECT_ID"
    echo "GITHUB_ID=<from step 4>"
    echo "GITHUB_SECRET=<from step 4>"
    echo "GOOGLE_CLIENT_ID=<from step 4>"
    echo "GOOGLE_CLIENT_SECRET=<from step 4>"
    echo "NEXTAUTH_SECRET=<from step 4>"
    echo "NEXTAUTH_URL=https://ai-news-bice.vercel.app"
    echo ""
    
    # Generate a sample .env.local
    echo ""
    echo "Generating .env.local.sample..."
    cat > .env.local.sample << EOF
# Auto-generated by setup.sh - copy to .env.local and fill in values

# GitHub OAuth
GITHUB_ID=
GITHUB_SECRET=

# Google OAuth
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# NextAuth
NEXTAUTH_URL=https://ai-news-bice.vercel.app
NEXTAUTH_SECRET=openssl rand -base64 32

# Vercel (for GitHub Actions)
VERCEL_TOKEN=
VERCEL_ORG_ID=$ORG_ID
VERCEL_PROJECT_ID=$PROJECT_ID
EOF
    
    echo -e "${GREEN}✓ Created .env.local.sample${NC}"
    echo ""
    echo "Next steps:"
    echo "1. Configure OAuth apps (GitHub + Google)"
    echo "2. Add environment variables to Vercel Dashboard"
    echo "3. Add secrets to GitHub Actions"
    echo "4. Push changes to trigger automatic deployment"
    echo ""
else
    echo -e "${RED}Project not linked. Run: vercel link${NC}"
fi
